import type { MenuItem } from '../types';
import { MENU_ITEMS_DATA } from './navigation';

export const rawProducts = [
  {
    id: 1752700000061,
    category: "Muebles",
    name: "Gavetero Orlviro 105",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 269,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3800/comoda-orlviro-105_3800236.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 82, height: 85.4, depth: 40 },
    materials: ["Aglomerado laminado"],
    colors: ["Marrón", "Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000062,
    category: "Muebles",
    name: "Gavetero Livluo 102",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 439,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3795/comoda-livluo-102_3795889.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 160, height: 89.9, depth: 40 },
    materials: ["MDF"],
    colors: ["Beige"],
    setType: "Sólido"
  },
  {
    id: 1752700000063,
    category: "Muebles",
    name: "Gavetero Livluo 103",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 375,
    oldPrice: 420,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3795/comoda-livluo-103_3795993.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 115, height: 89.8, depth: 40 },
    materials: ["MDF"],
    colors: ["Beige"],
    setType: "Sólido",
    ledLighting: true
  },
  {
    id: 1752700000064,
    category: "Muebles",
    name: "Gavetero Kailua 2393",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 389,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3792/comoda-kailua-2393-antracita_3792768.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 23 días laborales",
    dimensions: { width: 72, height: 77, depth: 45 },
    materials: ["Aglomerado laminado"],
    colors: ["Gris"],
    setType: "Partes separadas"
  },
  {
    id: 1752700000065,
    category: "Muebles",
    name: "Gavetero Kailua 2394",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 579,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3793/comoda-kailua-2394-antracita_3793054.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 23 días laborales",
    dimensions: { width: 100, height: 85, depth: 45 },
    materials: ["Aglomerado laminado", "Metal"],
    colors: ["Gris"],
    setType: "Partes separadas"
  },
  {
    id: 1752700000066,
    category: "Muebles",
    name: "Gavetero Marelbe 102",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 259,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3793/comoda-marelbe-102_3793222.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 23 días laborales",
    dimensions: { width: 72, height: 74, depth: 43 },
    materials: ["Madera"],
    colors: ["Marrón"],
    setType: "Sólido"
  },
  {
    id: 1752700000067,
    category: "Muebles",
    name: "Gavetero Comfivo Larmire 102",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 210,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3410/comoda-comfivo-larmire-102-blanco_3410627.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/3410/comoda-comfivo-larmire-102-negro_3410697.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 8 días laborales",
    dimensions: { width: 80, height: 75, depth: 40 },
    materials: ["MDF"],
    colors: ["Blanco", "Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000068,
    category: "Muebles",
    name: "Gavetero Comfivo Fersoe 100",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 226,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3790/comoda-comfivo-fersoe-100-cachemira_3790137.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/3790/comoda-comfivo-fersoe-100-blanco_3790134.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 8 días laborales",
    dimensions: { width: 141, height: 93, depth: 41 },
    materials: ["Aglomerado laminado"],
    colors: ["Beige", "Blanco"],
    setType: "Partes separadas",
    ledLighting: true
  },
  {
    id: 1752700000069,
    category: "Muebles",
    name: "Gavetero Comfivo Fersoe 104",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 289,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3790/comoda-comfivo-fersoe-104-cachemira_3790464.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/2643/comoda-comfivo-fersoe-104-blanco_2643088.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 8 días laborales",
    dimensions: { width: 120, height: 93, depth: 41 },
    materials: ["Aglomerado laminado"],
    colors: ["Beige", "Blanco"],
    setType: "Partes separadas",
    ledLighting: false
  },
  {
    id: 1752700000070,
    category: "Muebles",
    name: "Gavetero Alfere 121",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 220,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3777/comoda-alfere-121-blanco_3777376.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/3777/comoda-alfere-121-roble-wotan_3777382.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 10 días laborales",
    dimensions: { width: 80, height: 85.1, depth: 40 },
    materials: ["Madera"],
    colors: ["Blanco", "Marrón"],
    setType: "Sólido"
  },
  {
    id: 1752700000071,
    category: "Muebles",
    name: "Gavetero Sorsale 101",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 339,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3775/comoda-sorsale-101_3775144.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 103.2, height: 132, depth: 42 },
    materials: ["Madera", "Metal"],
    colors: ["Marrón", "Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000072,
    category: "Muebles",
    name: "Gavetero Austin 364",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 309,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/4127/comoda-austin-364-congo_4127427.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/3775/comoda-austin-364-roble-wotan_3775333.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 10 días laborales",
    dimensions: { width: 132, height: 91.2, depth: 35 },
    materials: ["Madera"],
    colors: ["Marrón"],
    setType: "Sólido",
    ledLighting: true
  },
  {
    id: 1752700000073,
    category: "Muebles",
    name: "Gavetero Sorsale 103",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 339,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3775/comoda-sorsale-103_3775347.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 193.2, height: 90.2, depth: 42 },
    materials: ["Madera", "Metal"],
    colors: ["Marrón", "Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000074,
    category: "Muebles",
    name: "Gavetero Sorsale 104",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 299,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3775/comoda-sorsale-104_3775509.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 153.2, height: 90.2, depth: 42 },
    materials: ["Madera", "Metal"],
    colors: ["Marrón", "Negro"],
    setType: "Sólido",
    ledLighting: true
  },
  {
    id: 1752700000075,
    category: "Muebles",
    name: "Gavetero Sorsale 105",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 239,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3775/comoda-sorsale-105_3775540.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 103.2, height: 90.2, depth: 42 },
    materials: ["Madera", "Metal"],
    colors: ["Marrón", "Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000076,
    category: "Muebles",
    name: "Gavetero Salcira 100",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 439,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3773/comoda-salcira-100_3773377.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 8 días laborales",
    dimensions: { width: 103, height: 80, depth: 39 },
    materials: ["MDF", "Vidrio templado"],
    colors: ["Marrón", "Gris"],
    setType: "Sólido"
  },
  {
    id: 1752700000077,
    category: "Muebles",
    name: "Gavetero Comfivo Virfera 100",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 239,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3780/comoda-comfivo-virfera-100-blanco-blanco-brillante_3780685.jpg?w=300&h=225&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 4 días laborales",
    dimensions: { width: 100, height: 85, depth: 40 },
    materials: ["Aglomerado laminado"],
    colors: ["Blanco"],
    setType: "Partes separadas",
    ledLighting: true
  },
  {
    id: 1752700000078,
    category: "Muebles",
    name: "Gavetero Sarasota 174",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 369,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3642/comoda-sarasota-174-madera-gris-blanco-brillante_3642181.jpg?w=300&h=225&p=fw", "https://img.muebles.es/detailed/3642/comoda-sarasota-174-roble-wotan-blanco-brillante_3642185.jpg?w=60&h=60&p=fw"],
    hint: "gavetero moderno",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 150, height: 68, depth: 40 },
    materials: ["Aglomerado laminado", "Vidrio"],
    colors: ["Gris", "Blanco", "Marrón"],
    setType: "Sólido"
  },
  {
    id: 1752700000154,
    category: "Muebles",
    name: "Mesa de centro SP5585",
    description: "Una mesa de centro elegante y funcional para tu hogar.",
    price: 439,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/4121/mesa-de-centro-sp5585_4121558.jpg?w=300&h=225&p=fw"],
    hint: "mesa de centro",
    deliveryTime: "Aproximadamente en 5 días laborales",
    dimensions: { width: 130, height: 38, depth: 60 },
    materials: ["Vidrio templado", "Metal"],
    colors: ["Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000247,
    category: "Sala",
    subcategory: "Muebles de TV",
    name: "Mueble TV Elbvelu 125",
    description: "Un gavetero elegante y funcional para tu hogar.",
    price: 119,
    rating: 4,
    reviews: 15,
    images: ["https://img.muebles.es/detailed/3617/mueble-tv-elbvelu-125-roble-artisan_3617765.jpg?w=300&h=225&p=fw"],
    hint: "mueble tv",
    deliveryTime: "Aproximadamente en 13 días laborales",
    dimensions: { width: 140, height: 36, depth: 40 },
    materials: ["Madera"],
    colors: ["Marrón"],
    setType: "Partes separadas"
  },
  {
    id: 1752700000301,
    category: "Puertas",
    name: "Puerta Interior de Roble Clásico",
    description: "Puerta de madera de roble macizo con un acabado natural, perfecta para interiores tradicionales.",
    price: 350,
    rating: 5,
    reviews: 22,
    images: ["https://picsum.photos/id/1013/400/300"],
    hint: "puerta interior madera",
    deliveryTime: "Aproximadamente en 15 días laborales",
    dimensions: { width: 90, height: 210, depth: 4 },
    materials: ["Madera de Roble"],
    colors: ["Marrón"],
    setType: "Sólido"
  },
  {
    id: 1752700000302,
    category: "Puertas",
    name: "Puerta Exterior de Metal Moderna",
    description: "Puerta de seguridad de alta resistencia con diseño minimalista en metal negro.",
    price: 780,
    rating: 4.5,
    reviews: 18,
    images: ["https://picsum.photos/id/1014/400/300"],
    hint: "puerta exterior seguridad",
    deliveryTime: "Aproximadamente en 25 días laborales",
    dimensions: { width: 100, height: 220, depth: 6 },
    materials: ["Metal", "Acero"],
    colors: ["Negro"],
    setType: "Sólido"
  },
  {
    id: 1752700000303,
    category: "Puertas",
    name: "Panel de Revestimiento 3D",
    description: "Panel decorativo de pared con diseño geométrico en 3D para crear un punto focal en cualquier habitación.",
    price: 85,
    rating: 4,
    reviews: 30,
    images: ["https://picsum.photos/id/1016/400/300"],
    hint: "revestimiento pared decorativo",
    deliveryTime: "Aproximadamente en 10 días laborales",
    dimensions: { width: 50, height: 50, depth: 2 },
    materials: ["PVC", "Yeso"],
    colors: ["Blanco"],
    setType: "Partes separadas"
  },
  {
    id: 1752700000401,
    category: "Herrajes y Accesorios",
    name: "Tirador de Gabinete Moderno",
    description: "Tirador de metal cepillado para gabinetes de cocina y baño.",
    price: 15,
    rating: 5,
    reviews: 50,
    images: ["https://picsum.photos/id/1077/400/300"],
    hint: "tirador metal",
    deliveryTime: "Aproximadamente en 5 días laborales",
    materials: ["Metal"],
    colors: ["Gris"],
  },
  {
    id: 1752700000501,
    category: "Electrodomésticos",
    name: "Estufa de Gas 6 Quemadores",
    description: "Estufa de acero inoxidable con 6 quemadores y horno de gran capacidad.",
    price: 950,
    rating: 4.8,
    reviews: 45,
    images: ["https://picsum.photos/id/201/400/300"],
    hint: "estufa acero inoxidable",
    deliveryTime: "Aproximadamente en 7 días laborales",
    materials: ["Acero"],
    colors: ["Gris"],
  },
];

const NON_PRODUCT_CATEGORIES = ['blog', 'proyectos', 'cotizar'];
export const CATEGORIES = (MENU_ITEMS_DATA as Omit<MenuItem, 'id'>[])
  .filter(item => !NON_PRODUCT_CATEGORIES.includes(item.key))
  .map(item => item.title)
  .sort();

export const COLOR_MAP: { [key: string]: string } = {
  'Blanco': '#FFFFFF',
  'Amarillo': '#FFEB3B',
  'Verde': '#4CAF50',
  'Verde azulado': '#009688',
  'Azul': '#2196F3',
  'Rojo': '#B71C1C',
  'Beige': '#D2B48C',
  'Marrón': '#795548',
  'Gris': '#9E9E9E',
  'Negro': '#212121',
};

export const MAX_PRICE = 20000;
export const MIN_PRICE = 0;

export const ALL_FINISHES = ['Brillo', 'Mate', 'Corrugado', 'Texturizado', 'Supermate'];
